[workspace]
resolver = "3"

members = [
    "crates/rgpui-component",
    "crates/rgpui-component-assets",
    "crates/rgpui-component-macros",
    "crates/rgpui-editor",
    "crates/rgpui-webview",

    "crates/rgpui-component/examples/app_assets",
    "crates/rgpui-component/examples/dialog_overlay",
    "crates/rgpui-component/examples/focus_trap",
    "crates/rgpui-component/examples/hello_world",
    "crates/rgpui-component/examples/input",
    "crates/rgpui-component/examples/sidebar",
    "crates/rgpui-component/examples/system_monitor",
    "crates/rgpui-component/examples/tooltip_top_edge",
    "crates/rgpui-component/examples/window_title",
]

[workspace.package]
edition = "2024"
publish = true
license = "Apache-2.0"

[workspace.dependencies]

rgpui-component = { path = "crates/rgpui-component" }
rgpui-component-macros = { path = "crates/rgpui-component-macros" }
rgpui-component-assets = { path = "crates/rgpui-component-assets" }
rgpui-webwiew = { path = "crates/rgpui-webview" }
rgpui-editor = { path = "crates/rgpui-editor" }

rgpui = "0.1"
rgpui-macros = "0.1"
rgpui-platform = "0.1"

# 错误处理库
anyhow = "1.0.86"
# 日志门面
log = { version = "0.4", features = ["kv_unstable_serde", "serde"] }
# 结构化追踪
tracing = "0.1"


notify = "8.2.0"
ropey = { version = "=2.0.0-beta.1", features = [
    "metric_lines_lf",
    "metric_utf16",
] }

rust-i18n = "4"

# JSON Schema 生成
schemars = { version = "1.2.1", features = ["indexmap2"] }
# 序列化/反序列化框架
serde = { version = "1.0.221", features = ["derive", "rc"] }
# JSON 处理
serde_json = { version = "1.0.144", features = ["preserve_order", "raw_value"] }
serde_repr = "0.1"

# 小数组优化的 Vec
smallvec = { version = "1.6", features = ["union", "const_new"] }

# 轻量级异步运行时
smol = "2.0"
# HTTP 客户端
reqwest = { version = "0.13", features = ["json","charset","http2","multipart","socks","stream"] }

lsp-types = { version = "0.97.0", features = ["proposed"] }

[workspace.lints.rust]
unexpected_cfgs = { level = "allow" }

[workspace.lints.clippy]
dbg_macro = "deny"
todo = "deny"

declare_interior_mutable_const = "deny"

redundant_clone = "deny"
disallowed_methods = "deny"

# We currently do not restrict any style rules
# as it slows down shipping code to Zed.
#
# Running ./script/clippy can take several minutes, and so it's
# common to skip that step and let CI do it. Any unexpected failures
# (which also take minutes to discover) thus require switching back
# to an old branch, manual fixing, and re-pushing.
#
# In the future we could improve this by either making sure
# Zed can surface clippy errors in diagnostics (in addition to the
# rust-analyzer errors), or by having CI fix style nits automatically.
style = { level = "allow", priority = -1 }

# Individual rules that have violations in the codebase:
type_complexity = "allow"
let_underscore_future = "allow"

# Motivation: We use `vec![a..b]` a lot when dealing with ranges in text, so
# warning on this rule produces a lot of noise.
single_range_in_vec_init = "allow"

# in Rust it can be very tedious to reduce argument count without
# running afoul of the borrow checker.
too_many_arguments = "allow"

# We often have large enum variants yet we rarely actually bother with splitting them up.
large_enum_variant = "allow"

# Boolean expressions can be hard to read, requiring only the minimal form gets in the way
nonminimal_bool = "allow"


